### ISSUE TITLE
Return 1 

### ISSUE THREAD

**Issue by hickford** [adrianaisemberg/CLAP#12] opened 2012-03-22 09:51 UTC
I like how CLAP applications given a bad command give back a useful message. They ought to fail in the Unix sense, ie. give a non-zero return code

```
$ git party ; echo  $?
git: 'party' is not a git command. See 'git --help'.
1
```

Whereas with a CLAP app:

```
 Verb 'party' was not found
 0
```

**Comment by adrianaisemberg** [comment] 2012-03-22 12:15
Interesting.
I'll design something and implement ASAP.

Thanks!

Adrian Aisemberg
vercue.com http://www.vercue.com
sharpregion.com http://www.sharpregion.com

On Thu, Mar 22, 2012 at 11:51 AM, Matt Hickford <
reply@reply.github.com

**Comment by hickford** [comment] 2012-03-22 19:07
Another thought: what happens if my verb method returns an int?

**Comment by adrianaisemberg** [comment] 2012-03-23 19:13
Fixed in 3.9.
Returns 1 or 0, according to whether an error occurred or not.

**Closed as completed by adrianaisemberg** 2012-03-23 19:13 UTC

**Comment by hickford** [comment] 2012-03-26 13:37
Thanks Adrian

**Comment by adrianaisemberg** [comment] 2012-03-26 13:41
All verbs are void by design, however, I'll consider changing it to allow returning values, although it will be a conflict to returning an int according to success/failure.

**Comment by hickford** [comment] 2012-03-26 15:19
Void verbs is sensible. If I want to exit with a specific code I will use [Environment.Exit](http://msdn.microsoft.com/en-us/library/system.environment.exit.aspx)

**Comment by adrianaisemberg** [comment] 2012-03-26 15:22
Cheers!
